version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sign-language-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - sign-language-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sign-language-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sign-language-network
    restart: unless-stopped

networks:
  sign-language-network:
    driver: bridge
