version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sign-language-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEBUG=true
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - sign-language-network
    restart: unless-stopped
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sign-language-frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - sign-language-network
    restart: unless-stopped

networks:
  sign-language-network:
    driver: bridge
